Update jshint pre-commit

diff --git a/jshint/pre-commit b/jshint/pre-commit
--- a/jshint/pre-commit
+++ b/jshint/pre-commit
@@ -18,27 +18,20 @@
 
 has_error=0
 
-which jshint > /dev/null
-if [ $? -gt 0 ]; then
-	echo "You need JSHint for this, install via 'npm install -g jshint'";
-	exit 1;
-fi
-
-if [ ! -f "jshint.conf" ]; then
-	echo "No jshint.conf exists"
-	exit 1;
-fi
-
-if [ ! -f "jshint_browser.conf" ]; then
-	echo "No jshint_browser.conf exists"
-	exit 1;
-fi
-
 # GIT_WORKING_DIR apparently it's $PWD, cache this path
 WORKING_DIR=$PWD
 
+jshint_path=$(which jshint 2>&1)
+if [ "$jshint_path" = "" ]; then
+	jshint_path="$WORKING_DIR/node_modules/.bin/jshint"
+	if [ ! -e $jshint_path ]; then
+		echo "JSHint isn't installed and it's required";
+		exit 1;
+	fi
+fi
+
 # Generate a tmp-dir-base-that doesn't overlap with others
-TMP_BASEDIR=/dev/shm/git_hook_$( date | sha1sum | cut -d" " -f1 );
+TMP_BASEDIR=$WORKING_DIR/.tmp_hooks/$( date | sha1sum | cut -d" " -f1 );
 # echo $WORKING_DIR;
 # echo $TMP_BASEDIR;
 for file in $(git diff-index --name-only --cached HEAD --diff-filter=AMCT); do
@@ -55,12 +48,26 @@ for file in $(git diff-index --name-only --cached HEAD --diff-filter=AMCT); do
 		# Create the directory for the TMP_WORKFILE
 		mkdir -p "$( dirname $TMP_WORKFILE )";
 
-		# Oh, what config file to use? The one for the files for node.js or the one for files for the browser
-		config_file="jshint.conf"
-		echo $file | grep "public\/javascripts\/" > /dev/null;
-		if [ $? -eq 0 ]; then
-			config_file="jshint_browser.conf"
-		fi
+		# Find config-file
+		config_file=
+		tpath=$(dirname $file);
+		tpath=$(realpath $tpath);
+		lpath=
+		while [ -d $tpath ] && [ "$lpath" != "$tpath" ]; do
+				tfile=$tpath/.jshintrc
+				if [ -f $tfile ]; then
+						config_file=$tfile
+						break;
+				fi
+
+				tfile=$tpath/jshint.conf
+				if [ -f $tfile ]; then
+						config_file=$tfile
+						break;
+				fi
+				lpath=$tpath
+				tpath=$(dirname $tpath);
+		done
 
 		# Get the staged file from the index and put it in our working dir, keep the path so it's easier to read.
 		git show "$show" > "$TMP_WORKFILE";
@@ -69,7 +76,12 @@ for file in $(git diff-index --name-only --cached HEAD --diff-filter=AMCT); do
 		cd "$TMP_BASEDIR";
 
 		# Run jshint on the files
-		jshint --config "${WORKING_DIR}/${config_file}" "$file"
+		if [ "$config_file" != "" ]; then
+			$jshint_path --config "${config_file}" "$file"
+		else
+			$jshint_path "$file"
+		fi
+
 		if [ $? -gt 0 ]; then
 			has_error=1;
 			echo "$file failed to validate in JSHint using ${config_file}"
@@ -86,6 +98,8 @@ for file in $(git diff-index --name-only --cached HEAD --diff-filter=AMCT); do
 	fi
 done;
 
-rm -rf "$TMP_WORKFILE";
+if [ -d "$TMP_BASEDIR" ]; then
+	find "$TMP_BASEDIR" -empty -delete
+fi
 
 exit $has_error
